/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SbEmojitton {
        "emoji": string;
        "position": "prepend" | "append";
        "text": string;
    }
}
declare global {
    interface HTMLSbEmojittonElement extends Components.SbEmojitton, HTMLStencilElement {
    }
    var HTMLSbEmojittonElement: {
        prototype: HTMLSbEmojittonElement;
        new (): HTMLSbEmojittonElement;
    };
    interface HTMLElementTagNameMap {
        "sb-emojitton": HTMLSbEmojittonElement;
    }
}
declare namespace LocalJSX {
    interface SbEmojitton {
        "emoji"?: string;
        "position"?: "prepend" | "append";
        "text"?: string;
    }
    interface IntrinsicElements {
        "sb-emojitton": SbEmojitton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sb-emojitton": LocalJSX.SbEmojitton & JSXBase.HTMLAttributes<HTMLSbEmojittonElement>;
        }
    }
}
